# Base de datos en memoria para tests
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Configuración JWT para tests
jwt:
  secret: test-secret-key-for-testing-purposes-only
  expiration: 3600000

  # Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.alkemy.alkywallet: DEBUG