name: Docker Image Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-login-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./alkywallet
          push: false
          tags: ${{vars.DOCKERHUB_USERNAME}}/turbowallet-backend:$(date-'%Y-%m-%d')-${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./alkywallet
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/turbowallet-backend:$(date-'%Y-%m-%d')-${{ github.sha }}