name: Docker Image Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image # This step builds the Docker image using the Dockerfile in the alkywallet directory
      run: |
        docker build \
        --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
        --build-arg USER_GENERATOR=${{ secrets.USER_GENERATOR }} \
        -t turbowallet-backend:${{ github.sha }} \
        ./alkywallet

    - name: Push Docker image
      run: |
        docker tag turbowallet-backend:${{ github.sha }} turbowallet-backend:${{ github.sha }}
        docker push turbowallet-backend:${{ github.sha }}