name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify Maven installation
        run: mvn --version
        working-directory: ./alkywallet

      - name: Build
        run: mvn clean install -DskipTests
        working-directory: ./alkywallet

      - name: Build Docker image
        run: |
          docker build \
            --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
            --build-arg USER_GENERATOR=${{ secrets.USER_GENERATOR }} \
            -t turbowallet-backend:${{ github.sha }} \
            ./alkywallet

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push turbowallet-backend:${{ github.sha }}

