name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Verify Maven installation
        run: mvn --version

      - name: Build
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Push Docker image
        run: docker push myapp:${{ github.sha }}

