name: Build and Deploy

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: TurboWallet-Backend # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Verify Maven installation
        run: mvn --version
        working-directory: ./alkywallet

      - name: Publish to GitHub Packages Apache Maven
        run: mvn clean package -DskipTests
        working-directory: ./alkywallet
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

